"""Add email column to users table

Revision ID: 772f27da5ac4
Revises: 06e725d36d32
Create Date: 2023-07-05 16:00:25.593579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772f27da5ac4'
down_revision = '06e725d36d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
